language: node_js
node_js:
    - "0.10"
services:
    - couchdb
env:
    global:
        - NODE_ENV=test
before_install:
    - npm install forever coffee-script -g
    - npm install cozy-controller -g
    - locate cozy-controller
    - sudo sed -i -e 's/^Defaults\tsecure_path.*$//' /etc/sudoers
    - sudo forever start -o forever-ds.log cozy-controller
    - ps aux | grep controller
    - sleep 5
    - cat forever-ds.log
    - curl http://localhost:9002/
    - cd ..

script: 'cake tests'

after_failure:
    - cat cozy-data-system/forever-ds.log
    - cat cozy-data-system/log/test.log
